### ISSUE TITLE
Steam Deck support required

### ISSUE THREAD

**Issue by klx1204** [Geocld/XStreaming-desktop#1]
Tested on steam deck's desktop. The Appimage package works perfectly.
Unfortunately, the Appimage is unable to be launched via steam client, also stuck the whole system for a while.
With some research, I figured out Greenlight works fluently via steam client on Steam Deck, both AUR and Appimage formats.
It would be great XStreaming works on Steam Deck.

**Comment by Geocld** [comment]
@klx1204 Thanks for your feedback. Currently, I don't have a physical Steam Deck device, but based on your feedback, it seems there might be a step missing in the installation process. You can try following the installation steps below:

1. Start into Desktop Mode
2. Download [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher/releases/download/v2.2.0/appimagelauncher-lite-2.2.0-travis995-0f91801-x86_64.AppImage) and rename this file to appimagelauncher.AppImage
3. Inside the folder where you downloaded AppImageLauncher, right click an empty area and Open Terminal to run these two 
commands:

chmod +x appimagelauncher.AppImage

./appimagelauncher.AppImage install

4. Download [XStreaming v1.0.3](https://github.com/Geocld/XStreaming-desktop/releases/download/v1.0.3/XStreaming-1.0.3.AppImage) and save this file in Home/Applications
5. Go to Start -> Utilities, right click on Xbox-xCloud, and Add to Steam
6. Switch into Steam Gaming Mode and try open XStreaming

Please try using the above installation process. Installing AppImageLauncher is particularly important, so please don't skip it. I look forward to your feedback!

**Comment by Geocld** [comment]
@klx1204 Thanks for your feedback. Based on your feedback, it seems to be an installation issue. You can refer to the documentation for installation.

[steamdeck-install](https://github.com/Geocld/XStreaming-desktop?tab=readme-ov-file#steamdeck-install)

**Comment by klx1204** [comment]
> @klx1204 Thanks for your feedback. Based on your feedback, it seems to be an installation issue. You can refer to the documentation for installation.
> 
> [steamdeck-install](https://github.com/Geocld/XStreaming-desktop?tab=readme-ov-file#steamdeck-install)

Perfectly works! Thanks!
