### ISSUE TITLE
登录报错

### ISSUE THREAD

**Issue by lyz337959725** [Geocld/XStreaming-desktop#2]
![image](https://github.com/user-attachments/assets/98440be1-bf98-410b-9cb3-07a4f5fbf8cf)

**Comment by Geocld** [comment]
@lyz337959725 可以升级到 [1.0.3](https://github.com/Geocld/XStreaming-desktop/releases/tag/v1.0.3) 试试，改版本对登录做了优化

**Comment by lyz337959725** [comment]
可以了  多谢
